#%RAML 1.0 DataType
    properties:
        movieId:
          type: number
          required: true
        movieTitle:
          type: string
          required: true
        yearReleased:
          type: string
          required: true
        avgRating:
          type: number
          required: true
        duration:
          type: string
          required: true
        genre:
          type: string
          required: true