#%RAML 1.0 DataType
properties:
        movieTitle:
          type: string
          required: true
        timeBooked:
          type: string
          required: true
        noOfSeats:
          type: number
          required: true
        screen:
          type: number
          required: true
