#%RAML 1.0 DataType
properties:
    filmID:
      type: number
      required: false
    filmName:
      type: string
      required: true
    yearReleased:
      type: number
      required: true
    avgRating:
      type: number
      required: true
    duration:
      type: number
      required: true
    genre:
      type: string
      required: true